"""NVIDIA Nemotron AI provider via Nebius Token Factory."""

import json
import os
import re

import httpx

from anchor.actions.models import ActionRequest
from anchor.contracts.models import Contract
from anchor.contracts.parser import parse_contract
from anchor.providers.base import IntentProvider, ProviderError

DEFAULT_NEBIUS_BASE_URL = "https://api.studio.nebius.ai/v1"
DEFAULT_NEBIUS_MODEL = "nvidia/llama-3.1-nemotron-70b-instruct"


def _clean_json_response(content: str) -> str:
    """Extract JSON content from markdown code fences or whitespace."""
    stripped = content.strip()
    match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", stripped)
    if match:
        return match.group(1).strip()
    return stripped


class NebiusProvider(IntentProvider):
    """
    Inference provider connecting to NVIDIA Nemotron models hosted on Nebius Token Factory.

    All LLM output is strictly validated and treated as untrusted.
    """

    def __init__(
        self,
        api_key: str | None = None,
        base_url: str | None = None,
        model: str | None = None,
    ) -> None:
        self.api_key = api_key or os.getenv("NEBIUS_API_KEY", "")
        if not self.api_key:
            raise ProviderError("NEBIUS_API_KEY is not set or empty")

        self.base_url = (base_url or os.getenv("NEBIUS_BASE_URL", DEFAULT_NEBIUS_BASE_URL)).rstrip("/")
        self.model = model or os.getenv("NEBIUS_MODEL", DEFAULT_NEBIUS_MODEL)

    def generate_contract(self, goal: str) -> Contract:
        """Query Nemotron to synthesize a structured contract for the specified goal."""
        system_prompt = (
            "You are ANCHOR's contract generator. Convert the user's goal into a strict "
            "JSON safety contract. You MUST respond with ONLY a valid JSON object matching this schema:\n"
            "{\n"
            '  "goal": string,\n'
            '  "allowed_paths": [string],\n'
            '  "forbidden_paths": [string],\n'
            '  "allowed_commands": [string],\n'
            '  "destructive_requires_approval": boolean,\n'
            '  "verification_command": string or null\n'
            "}\n"
            "Do not include any explanations, greetings, or commentary outside the JSON."
        )

        user_prompt = f"Goal: {goal}"

        response_text = self._chat_completion(system_prompt, user_prompt)
        cleaned_json = _clean_json_response(response_text)

        try:
            return parse_contract(cleaned_json)
        except Exception as err:
            raise ProviderError(f"Failed to validate contract generated by Nemotron: {err}") from err

    def propose_actions(self, goal: str, contract: Contract) -> list[ActionRequest]:
        """Ask Nemotron to propose structured candidate actions to fulfill the goal."""
        system_prompt = (
            "You are an AI developer proposing actions to complete a goal within contract boundaries. "
            "Respond with ONLY a JSON list of action objects:\n"
            "[\n"
            "  {\n"
            '    "type": "read_file" | "write_file" | "delete_file" | "run_command",\n'
            '    "target": string,\n'
            '    "content": string or null,\n'
            '    "args": [string] or null\n'
            "  }\n"
            "]"
        )
        user_prompt = (
            f"Goal: {goal}\n"
            f"Allowed paths: {contract.allowed_paths}\n"
            f"Forbidden paths: {contract.forbidden_paths}\n"
            f"Allowed commands: {contract.allowed_commands}"
        )

        response_text = self._chat_completion(system_prompt, user_prompt)
        cleaned_json = _clean_json_response(response_text)

        try:
            items = json.loads(cleaned_json)
            if not isinstance(items, list):
                raise ProviderError("Action proposal must be a JSON list")
            return [ActionRequest(**item) for item in items]
        except Exception as err:
            raise ProviderError(f"Failed to parse action proposals from Nemotron: {err}") from err

    def _chat_completion(self, system_prompt: str, user_prompt: str) -> str:
        """Send chat completion request to Nebius Token Factory endpoint."""
        url = f"{self.base_url}/chat/completions"
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": 0.1,
        }

        try:
            with httpx.Client(timeout=30.0) as client:
                resp = client.post(url, headers=headers, json=payload)
                if resp.status_code != 200:
                    raise ProviderError(
                        f"Nebius API returned error {resp.status_code}: {resp.text}"
                    )
                data = resp.json()
                return str(data["choices"][0]["message"]["content"])
        except httpx.RequestError as err:
            raise ProviderError(f"Network error communicating with Nebius API: {err}") from err
